apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: component-python-public
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: component-python-public
    app.kubernetes.io/part-of: e2e-python-personal
  name: component-python-public
  namespace: e2e-demo-tnaf
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: component-python-public
status:
  loadBalancer: {}
